version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: idle_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 400111
      POSTGRES_DB: gacha
    ports:
      - "5432:5432"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "gacha"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  gacha-service:
    build: ./gacha-service
    container_name: gacha-service
    restart: always
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 400111
      POSTGRES_DB: gacha
      PGHOST: postgres
      PGPORT: 5432

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    restart: always
    depends_on:
      - postgres
    ports:
      - "5002:5002"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 400111
      POSTGRES_DB: gacha
      PGHOST: postgres
      PGPORT: 5432

  shop-service:
    build: ./shop-service
    container_name: shop-service
    restart: always
    depends_on:
      - postgres
    ports:
      - "5003:5003"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 400111
      POSTGRES_DB: gacha
      PGHOST: postgres
      PGPORT: 5432

  idle-service:
    build: ./idle-service
    container_name: idle-service
    restart: always
    depends_on:
      - postgres
    ports:
      - "5004:5004"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 400111
      POSTGRES_DB: gacha
      PGHOST: postgres
      PGPORT: 5432

  client:
    build: ./client
    container_name: client_side
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - gacha-service
      - inventory-service
      - shop-service
      - idle-service

volumes:
  postgres_data:
